volumes:
  mongo_data:

services:
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: 'root'
        MONGO_INITDB_ROOT_PASSWORD: 'root'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      # Porta para acessar o Kafka de fora do Docker (da sua máquina, onde rodam os scripts Python)
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # Endereço que o Kafka "anuncia" para clientes externos (seus scripts Python)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
